spring:
  config:
    import: properties/app-properties.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog.sql

server:
  port: 8082

springdoc:
  api-docs:
    path: /support/swagger
  swagger-ui:
    path: /support/swagger-ui.html
    disable-swagger-default-url: true


kafka:
  bootstrap-servers: localhost:29092